name: Version Check against Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distribution: [temurin, corretto, liberica]
        version: [8, 11, 17 ,21]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: ${{ matrix.distribution }}
            java-version: ${{ matrix.version }}
