
name: Check dist

on:
  workflow_dispatch:

jobs:
  call-check-dist:
    name: Check dist/
    uses: actions/reusable-workflows/.github/workflows/check-dist.yml@main
    with:
      node-version: '20.x'
