name: Version Check against Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distribution: [microsoft, oracle, temurin, corretto, liberica, dragonwell, sapmachine, graalvm]
        version: [8, 11, 17 ,21, 22]
        oracle-exclude: [8, 11]
        exclude:
          - distribution: microsoft
            version: 8
          - distribution: microsoft
            version: 8
          - distribution: microsoft
            version: ${{ matrix.oracle-exclude }}
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: ${{ matrix.distribution }}
            java-version: ${{ matrix.version }}
