name: GraalVM Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: ['17','21','22']
        os: ['ubuntu-latest','windows-latest','macos-13','macos-14']
    steps:
      - name: Checkout Code
        uses: actions/cache@v3
      - name: Steup Java with 21
        uses: graalvm/setup-java@fniephaus/graalvm
        with: 
          distribution: graalvm
          java-version: ${{ matrix.distribution }}
      - name: Application Testing
        run: |
          java -cp java HelloWorldAppApplication
          # native-image -cp java HelloWorldApp
