name: GraalVM Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: ['21']
        os: ['ubuntu-latest']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Steup Java with 21
        uses: graalvm/setup-java@fniephaus/graalvm
        with: 
          distribution: graalvm
          java-version: ${{ matrix.distribution }}
      - name: Maven Test
        run: mvn clean install
      - name: Application Testing
        run:  |
          timeout 15s mvn exec:java
          if [ $? -eq 124 ]; then
            echo "Process timed out"
          else
            echo "Process finished with exit code $?"
          fi
