name: GraalVM Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: ['21']
        os: ['ubuntu-latest']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Steup Java with 21
        uses: graalvm/setup-java@fniephaus/graalvm
        with: 
          distribution: graalvm
          java-version: ${{ matrix.distribution }}
      - name: Build with Maven
        run: mvn clean install
      - name: Application Test
        run: native-image -cp target/classes HelloWorldAppApplication
