name: Test Java Setup

on:
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Update Dependency
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install sbt
        uses: sbt/setup-sbt@v1
