name: Test Java Setup

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  setup-java:
    runs-on: ubuntu-latest
    name: Set up JDK

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
