name: Ubuntu zlib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 11
          architecture: 'x86'
